### ISSUE TITLE
Not remembering most saved words, cannot save new words since the last update (v1.9-r2).

### ISSUE THREAD

**Issue by cb2T5rju** [AnySoftKeyboard/AnySoftKeyboard#1328]
### Steps to reproduce
1. Type saved or unsaved word (not remembered)
2. Touch word to save it
3. "Touch again to save" not responsive to touch

### Expected behaviour
Until the previous update I would add words to the dictionary as per the usual method, and then the app would remember them and not autocorrect (ie "lol" would not be autocorrected to "mol" after I'd added "lol" to the dictionary).

### Actual behaviour
Since the update two issues have arisen. The first is that (despite still appearing in the dictionary in the app itself) the keyboard does not remember most or all saved words (cannot confirm if it is all of them, but it has been a large number of confirmed saved words).

When I attempt to add/re-add a word to the dictionary list the "Touch again to save" prompt is unresponsive. No matter how many times it has been attempted it no longer saves words.

When I opened the dictionary to see if the words had all been erased, they were all present. For a brief period the keyboard returned to correctly remembering the words, before reverting once again to having forgotten all of them (over the course of all of this, however, I have been unable to add new saved words).

**Android OS version:** 7.1.1

**Device manufacturer and model:** Motorolla Moto E4 Plus

**List of installed add-ons (like languages, or themes):** Lean Dark stock theme used, English QWERTY Latin stock kebyoard used (no other add-ons)

**Comment by menny** [comment]
how many words do you have stored? I wasn't able to reproduce this issue.

**Comment by asaparov** [comment]
I have the same problem on Android 8.0.0 with HTC 10. Im using the English QWERTY Latin keyboard with Lean Dark Grey theme. No other arsons either. I have almost 500 custom words in my dictionary.

**Comment by GoranGharib** [comment]
I have this problem too can't save the new words to personal dict please fix.

Tried on: HTC 10 , Huwaei Honor 8 , Galaxy s6 Edge....etc

**Comment by farhaduli** [comment]
i have a same problem with new update of keyboard , i can't save new words and keyboard not suggest my saved words ?

**Comment by cb2T5rju** [comment]
I have quite a few saved words. I can suggest words to save but I can't confirm them (the second click). For a while uninstalling and reinstalling would make it work for a very short period of time (same with opening the app and restoring the dictionary).

**Comment by menny** [comment]
This should be fixed with the latest release.

**Comment by doodhout** [comment]
Still a problem for me, ASK v.1.10-r1. The trick to temporarily fix by opening the word list doesn't even work.

**Comment by jonhaddow** [comment]
Same issue here. ASK v1.10.606

**Comment by Jonathan-00** [comment]
Same issue. Galaxy A53, android 14, oneui 6.0. Funny enough, I was just now able to save "oneui", but not "a" or "I"
