### ISSUE TITLE
Cursor (caret) position randomly moves 1-2 steps back

### ISSUE THREAD

**Issue by amanharwara** [AnySoftKeyboard/AnySoftKeyboard#2320]
### Steps to reproduce
1. Seems to happen almost randomly, so I don't really have any proper steps to reproduce other than to just type.

### Expected behaviour
Regular typing should work as intended.

### Actual behaviour
Randomly when typing, the cursor position moves 1-2 steps back messing up the whole word.

**Android OS version:** 9

**Device manufacturer and model:** Huawei/Honor BND-AL10

**List of installed add-ons (like languages, or themes):**
I don't have any extra add-ons. Here are the inbuilt settings I'm using:
Keyboard: QWERTY Latin keyboard with symbols (on long press)
Theme: AOSP Dark theme

Let me know if I need to provide any other details.

**Comment by jlemonde** [comment]
It happens to me too, although only when typing fast. Really annoying.

**Comment by fuselier** [comment]
Im having the same issue

**Comment by menny** [comment]
I hope that the changes made in the upcoming release will fix this.

**Comment by PrSunflower** [comment]
@menny Thanks for considering a fix. This is definitely my number 1 bug with ASK.

Issue #1875 already discusses of this and some users have suggested that disabling the animations helps.

**Comment by menny** [comment]
Would you mind trying out https://github.com/AnySoftKeyboard/AnySoftKeyboard/suites/1470313885/artifacts/25293257

**Comment by amanharwara** [comment]
> Would you mind trying out https://github.com/AnySoftKeyboard/AnySoftKeyboard/suites/1470313885/artifacts/25293257

Have used this for about 1½ hrs now and haven't had this issue so far but I'll test it a bit more and let you know again.

**Comment by menny** [comment]
that's amazing to hear!

**Comment by PrSunflower** [comment]
Hi @menny . I have been using your fix since 24h and I am happy to say that I don't have the problem anymore! 🥳
With your fix I am using ASK with Full animations and so far the cursor is behaving properly. Not skipping inputs nor jumping between words.

However if I remember well the problem was even worse when the phone is doing CPU-intensive tasks in the background. I haven't tested your fix in this situation.

**Comment by menny** [comment]
good to hear.

Thank you all for testing, this means a lot.

**Comment by PrSunflower** [comment]
@Menny Hello, I have been using your fix for one week now and when though there are 0 problems with the animations, there is a bug that didn't happen before.

Let's say that I am typing the word "thank" (in English) and I position my cursor behind the 'k". I erase "han" and start typing again, ASK will try to autocorrect the new letters I am typing.

### Screenshots

![Screenshot_20201116-094304](https://user-images.githubusercontent.com/59576952/99231778-5dd87300-27f1-11eb-8ec9-e12e5b442042.png)

This didn't happen before and has caused me to write mistakes sometimes:

![Screenshot_20201116-094317](https://user-images.githubusercontent.com/59576952/99231842-73e63380-27f1-11eb-9572-87cfe1071776.png)

**Comment by menny** [comment]
This was fixed in a later commit
please, verify https://github.com/AnySoftKeyboard/AnySoftKeyboard/suites/1506540992/artifacts/26396712

**Comment by PrSunflower** [comment]
@menny Hi, I have downloaded and installed this APK (Testing build 1.10.1651, version code 6821) but the error is still here.

I have been using it for several days, here are some screenshots:

### Example 1

![Screenshot_20201119-154408](https://user-images.githubusercontent.com/59576952/99975844-ff883300-2da2-11eb-9138-d93bd185e3f6.png)

![Screenshot_20201119-154415](https://user-images.githubusercontent.com/59576952/99975868-07e06e00-2da3-11eb-9af9-09f0c20659b3.png)

### Example 2

![Screenshot_20201119-155133](https://user-images.githubusercontent.com/59576952/99975935-1f1f5b80-2da3-11eb-89f5-6479c1e816f5.png)

![Screenshot_20201119-155137](https://user-images.githubusercontent.com/59576952/99975944-221a4c00-2da3-11eb-8c61-239981bd3710.png)


### Example 3

![Screenshot_20201120-132919](https://user-images.githubusercontent.com/59576952/99975956-247ca600-2da3-11eb-8dca-82571cbfaf54.png)

![Screenshot_20201120-132930](https://user-images.githubusercontent.com/59576952/99975967-27779680-2da3-11eb-8f84-f6a54b1d8e76.png)


### Example 4

![Screenshot_20201123-095126](https://user-images.githubusercontent.com/59576952/99975984-2b0b1d80-2da3-11eb-8f05-ff0b2b870a1e.png)

![Screenshot_20201123-095130](https://user-images.githubusercontent.com/59576952/99975991-2d6d7780-2da3-11eb-8f0a-62a2c92bc7b5.png)


### Example 5, other languages are affected too

![Screenshot_20201117-020416](https://user-images.githubusercontent.com/59576952/99976000-2fcfd180-2da3-11eb-84c9-dc2b42709bbc.png)




<br>

<br>

Do you want me to create a new issue?
