### ISSUE TITLE
After typing and deleting the default emoji - some weird behaviour (underlined and then deleted text)

### ISSUE THREAD

**Issue by DimaM-BeStreet** [AnySoftKeyboard/AnySoftKeyboard#2972]
https://github.com/user-attachments/assets/92e8ff8e-56a1-4652-af93-825a62f9262d

### Steps to reproduce
1. write any text
2. add the default emoji (the left-bottom emoji button)
3. delete the emoji
4. watch the last typed text get underscored
5. type anything - see the underscored text get deleted (as if the 'insert key' was on)

### Expected behaviour
steps 4 and 5 should not happen, only the emoji should have been deleted

### Actual behaviour
steps 4 and 5

**Android OS version:**
11

**Device manufacturer and model:**
Samsung galaxy s10e

**List of installed add-ons (like languages, or themes):**
hebrew

https://user-images.githubusercontent.com/29048052/132015013-4441c397-58db-4948-87a1-e80624040ad1.mp4

**Comment by DimaM-BeStreet** [comment]
Can you guys let me download the latest version on android so i can test it
for you?

**Comment by menny** [comment]
You can download from https://github.com/AnySoftKeyboard/AnySoftKeyboard/suites/4239552026/artifacts/109874325

**Comment by DimaM-BeStreet** [comment]
Got to it pretty late, tried to open it from my android but it said 'app
was not installed', so.... idk

The problem is still there 🙌

**Comment by menny** [comment]
verified locally with the latest release. The bug was fixed

**Comment by DimaM-BeStreet** [comment]
Thank you! finally hehe
do you mean the version 1.12.786? i got it and the bug is still there, live an kickin'

**Comment by menny** [comment]
I'm unable to reproduce that. Can you share the sequence or video again?

**Comment by DimaM-BeStreet** [comment]
Sure, I've updated the video on the main first issue post, hope this helps!

**Comment by menny** [comment]
I can not reproduce this. I've tried to reproduce this on several devices and it does not been reproduced. Have you seen this happening on different devices?

**Comment by DimaM-BeStreet** [comment]
i've upgraded my phone about a year ago, so when i originally posted this issue i had a samsung s10e, now i have asus zenfone 10 (with the same problem)

Is it possible the problem is not from AnySoftKeyboard?
can it be coming from the Hebrew Language Pack?

**Comment by reu63417-cmd** [comment]
Hbb

**Comment by jonathanhernadezvlzq121534-a11y** [comment]
No sé puede
