### ISSUE TITLE
double entries in clipboard.

### ISSUE THREAD

**Issue by nihal697** [AnySoftKeyboard/AnySoftKeyboard#3452]
### Steps to reproduce
1.copy anything
2. long press clipboard button to see history

### Expected behaviour
should only show single entry 

### Actual behaviour
shows double entry

**Android OS version: 12**

**Device manufacturer and model:xiaomi redmi note 11
![Screenshot_20220731-021846_KISS launcher](https://user-images.githubusercontent.com/47318989/181995695-11bee479-b065-4fa2-980b-56fa5d3030bf.png)
**

**List of installed add-ons (like languages, or themes):**

**Comment by DanielKonopka** [comment]
Exactly the same here. Every clipboard entry is doubled. Very cumbersome having to remove double entries manually all the time. It wasn't happening in earlier versions (1.11.177) of Anysoftkeyboard. I kindly ask you to fix it. The keyboard is fantastic otherwise.

Anysoftkeyboard 1.11.582
Android OS 10
EMUI 10.1.1.210

**Comment by menny** [comment]
This was fixed with the latest beta. Thanks for reporting

**Comment by Zoomaaa** [comment]
Issue still happening on version 1.11.7137

**Comment by Johnny1000** [comment]
Still happening to me too.

- AnySoftKeyboard version 1.11.7137, installed from F-Droid.
- Phone: Samsung Galaxy A32 5G, model SM-A326B/DS
- Android version: 13.
- One UI-version: 5.1
- Google Play system update: 01. of july 2023.
(This phone can not be updated further than Android 13.)
- Android security update: 01. of august 2024.

**Comment by nihal697** [comment]
> The same "double entries in clipboard" issue. AnySoftKeyboard version 1.11.7137, installed from F-Droid. Phone: Xiaomi POCO M6 PRO 4G. OS: Hyper 1.0.1.0.UNFIDXM Android version: 14.
> 
> The same app version (AnySoftKeyboard V.1.11.7137) is installed on a Xiaomi Redmi Note 8 Pro smartphone (Android version: 09; OS: MIUI Global Stable 11.0.2.0(PGGIDXM)) and there's no such issue. I'm inclined to think the issue appeared due to an android version, if the android version is above the 9th version, then the mentioned issue might appear.

Hi, the issue was fixed actually and isnt there on latest beta/alpha.

**Comment by Vanessa-Eve** [comment]
> > The same "double entries in clipboard" issue. AnySoftKeyboard version 1.11.7137, installed from F-Droid. Phone: Xiaomi POCO M6 PRO 4G. OS: Hyper 1.0.1.0.UNFIDXM Android version: 14.
> > The same app version (AnySoftKeyboard V.1.11.7137) is installed on a Xiaomi Redmi Note 8 Pro smartphone (Android version: 09; OS: MIUI Global Stable 11.0.2.0(PGGIDXM)) and there's no such issue. I'm inclined to think the issue appeared due to an android version, if the android version is above the 9th version, then the mentioned issue might appear.
> 
> Hi, the issue was fixed actually and isnt there on latest beta/alpha.

I wish, but alas...Perhaps, I've missed smth., but could you clarify about which version you wrote? Because the latest AnySoftKeyboard version available 
![Screenshot_2024-12-26-00-40-47-657_com opera browser-edit](https://github.com/user-attachments/assets/7e8b588b-972b-4c63-9c08-08cc1ab8e0f9)
on F-droid is the Version 1.11.7137 (7137) (https://f-droid.org/packages/com.menny.android.anysoftkeyboard/), and that is the one I wrote about.

**Comment by nihal697** [comment]
> > > The same "double entries in clipboard" issue. AnySoftKeyboard version 1.11.7137, installed from F-Droid. Phone: Xiaomi POCO M6 PRO 4G. OS: Hyper 1.0.1.0.UNFIDXM Android version: 14.
> > > The same app version (AnySoftKeyboard V.1.11.7137) is installed on a Xiaomi Redmi Note 8 Pro smartphone (Android version: 09; OS: MIUI Global Stable 11.0.2.0(PGGIDXM)) and there's no such issue. I'm inclined to think the issue appeared due to an android version, if the android version is above the 9th version, then the mentioned issue might appear.
> > 
> > 
> > Hi, the issue was fixed actually and isnt there on latest beta/alpha.
> 
> I wish, but alas...Perhaps, I've missed smth., but could you clarify about which version you wrote? Because the latest AnySoftKeyboard version available ![Screenshot_2024-12-26-00-40-47-657_com opera browser-edit](https://private-user-images.githubusercontent.com/192604990/398601212-7e8b588b-972b-4c63-9c08-08cc1ab8e0f9.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUxNjM2ODgsIm5iZiI6MTczNTE2MzM4OCwicGF0aCI6Ii8xOTI2MDQ5OTAvMzk4NjAxMjEyLTdlOGI1ODhiLTk3MmItNGM2My05YzA4LTA4Y2MxYWI4ZTBmOS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyNVQyMTQ5NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yN2ZkMmQ0NjZjMDJlZTFkZmVjNWZjZjhhMDczYzBkYWMzOTc1MDZlZDQyOTIwZGQxZjU2MGIxNDVmM2ExMTg1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.lEKTe8MjLAKnoI7oJdT0JlMsLT9L6bFRn8UhpalUKMs) on F-droid is the Version 1.11.7137 (7137) (https://f-droid.org/packages/com.menny.android.anysoftkeyboard/), and that is the one I wrote about.

The fdroid version is quite old actually. I always recommend people to use the latest beta/alpha from play store or github actions respectively.

**Comment by Vanessa-Eve** [comment]
> > > > The same "double entries in clipboard" issue. AnySoftKeyboard version 1.11.7137, installed from F-Droid. Phone: Xiaomi POCO M6 PRO 4G. OS: Hyper 1.0.1.0.UNFIDXM Android version: 14.
> > > > The same app version (AnySoftKeyboard V.1.11.7137) is installed on a Xiaomi Redmi Note 8 Pro smartphone (Android version: 09; OS: MIUI Global Stable 11.0.2.0(PGGIDXM)) and there's no such issue. I'm inclined to think the issue appeared due to an android version, if the android version is above the 9th version, then the mentioned issue might appear.
> > > 
> > > 
> > > Hi, the issue was fixed actually and isnt there on latest beta/alpha.
> > 
> > 
> > I wish, but alas...Perhaps, I've missed smth., but could you clarify about which version you wrote? Because the latest AnySoftKeyboard version available ![Screenshot_2024-12-26-00-40-47-657_com opera browser-edit](https://private-user-images.githubusercontent.com/192604990/398601212-7e8b588b-972b-4c63-9c08-08cc1ab8e0f9.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUxNjM2ODgsIm5iZiI6MTczNTE2MzM4OCwicGF0aCI6Ii8xOTI2MDQ5OTAvMzk4NjAxMjEyLTdlOGI1ODhiLTk3MmItNGM2My05YzA4LTA4Y2MxYWI4ZTBmOS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyNVQyMTQ5NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yN2ZkMmQ0NjZjMDJlZTFkZmVjNWZjZjhhMDczYzBkYWMzOTc1MDZlZDQyOTIwZGQxZjU2MGIxNDVmM2ExMTg1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.lEKTe8MjLAKnoI7oJdT0JlMsLT9L6bFRn8UhpalUKMs) on F-droid is the Version 1.11.7137 (7137) (https://f-droid.org/packages/com.menny.android.anysoftkeyboard/), and that is the one I wrote about.
> 
> The fdroid version is quite old actually. I always recommend people to use the latest beta/alpha from play store or github actions respectively. Current beta that i use is version 1.12.762

Thank you for the info. After reading your reply, I tried to find out the beta version and I couldn't. There is no beta, no alpha version on GitHub, in Google Play Store or just some third party website.
Could you enlighten me where I can get AnySoftKeyboard version 1.12.762?


![Screenshot_2024-12-26-01-14-29-415_com opera browser-edit](https://github.com/user-attachments/assets/62821f1c-ec02-4dae-a574-f5c6dcb1681a)
![Screenshot_2024-12-26-02-04-08-519_com opera browser-edit](https://github.com/user-attachments/assets/bf97f6d3-f0e1-496f-a572-fc1efb5e36ec)

**Comment by nihal697** [comment]
> > > > > The same "double entries in clipboard" issue. AnySoftKeyboard version 1.11.7137, installed from F-Droid. Phone: Xiaomi POCO M6 PRO 4G. OS: Hyper 1.0.1.0.UNFIDXM Android version: 14.
> > > > > The same app version (AnySoftKeyboard V.1.11.7137) is installed on a Xiaomi Redmi Note 8 Pro smartphone (Android version: 09; OS: MIUI Global Stable 11.0.2.0(PGGIDXM)) and there's no such issue. I'm inclined to think the issue appeared due to an android version, if the android version is above the 9th version, then the mentioned issue might appear.
> > > > 
> > > > 
> > > > Hi, the issue was fixed actually and isnt there on latest beta/alpha.
> > > 
> > > 
> > > I wish, but alas...Perhaps, I've missed smth., but could you clarify about which version you wrote? Because the latest AnySoftKeyboard version available ![Screenshot_2024-12-26-00-40-47-657_com opera browser-edit](https://private-user-images.githubusercontent.com/192604990/398601212-7e8b588b-972b-4c63-9c08-08cc1ab8e0f9.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUxNjM2ODgsIm5iZiI6MTczNTE2MzM4OCwicGF0aCI6Ii8xOTI2MDQ5OTAvMzk4NjAxMjEyLTdlOGI1ODhiLTk3MmItNGM2My05YzA4LTA4Y2MxYWI4ZTBmOS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyNVQyMTQ5NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yN2ZkMmQ0NjZjMDJlZTFkZmVjNWZjZjhhMDczYzBkYWMzOTc1MDZlZDQyOTIwZGQxZjU2MGIxNDVmM2ExMTg1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.lEKTe8MjLAKnoI7oJdT0JlMsLT9L6bFRn8UhpalUKMs) on F-droid is the Version 1.11.7137 (7137) (https://f-droid.org/packages/com.menny.android.anysoftkeyboard/), and that is the one I wrote about.
> > 
> > 
> > The fdroid version is quite old actually. I always recommend people to use the latest beta/alpha from play store or github actions respectively. Current beta that i use is version 1.12.762
> 
> Thank you for the info. After reading your reply, I tried to find the beta version and I couldn't. There is no beta/alpha version on GitHub, in Google Play Store or on any third party website (according to Google search engine results). Could you enlighten me from where I can download AnySoftKeyboard version 1.12.762? I found v. 1.12.138 on apkmirror. com. Anyway, you helped me to solve the issue. The version 1.12.138 works fine, there's no more "double entries in clipboard" issue. THANK YOU!
> 
> ![Screenshot_2024-12-26-01-14-29-415_com opera browser-edit](https://private-user-images.githubusercontent.com/192604990/398603915-62821f1c-ec02-4dae-a574-f5c6dcb1681a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUxODI1MTgsIm5iZiI6MTczNTE4MjIxOCwicGF0aCI6Ii8xOTI2MDQ5OTAvMzk4NjAzOTE1LTYyODIxZjFjLWVjMDItNGRhZS1hNTc0LWY1YzZkY2IxNjgxYS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyNlQwMzAzMzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZjg1NzNmNWQ5NmU3YWNkZGRmOWQ4NzkyOWQ0NTJlMTZhNTViZTg3ZDlkOWNkOTBiZTY0NmM1Njk2ZDk0OTEzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.EIzZlBtOCkJpN24N7lDXTkHmajWLd6mvCq7IHerJnG4) ![Screenshot_2024-12-26-02-04-08-519_com opera browser-edit](https://private-user-images.githubusercontent.com/192604990/398603929-bf97f6d3-f0e1-496f-a572-fc1efb5e36ec.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUxODI1MTgsIm5iZiI6MTczNTE4MjIxOCwicGF0aCI6Ii8xOTI2MDQ5OTAvMzk4NjAzOTI5LWJmOTdmNmQzLWYwZTEtNDk2Zi1hNTcyLWZjMWVmYjVlMzZlYy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyNlQwMzAzMzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02Y2IyYzAyODIxYTczYjNlOTM5YTQ3NzJlYTZiMTI3MzEzZjRkMzc3OWUxOGZmMmJmYWQyODIxNmFhZDQ4ZTY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.U9MC0p_rI-1J_Lb2rKsWkqpvPD2DYmTCxIVgeGjF-5g)

you need to join beta program on play store in the app page, it is usually at the bottom of the page. Once you have joined it you will get beta updates.

for alpha you need to go to github actions menu and there find the title ime main alpha, and after clicking on it you scroll down to the bottom and download the apks file.
for example https://github.com/AnySoftKeyboard/AnySoftKeyboard/actions/runs/12484579720

do note that both cant be upgraded over due to signature mismatch so you need to clean install the app if switching between beta/alpha.

if you are comfortable i post the beta builds in this telegram channel here as well for my own purpose.
https://t.me/fossbeta

**Comment by Vanessa-Eve** [comment]
> > > > > > The same "double entries in clipboard" issue. AnySoftKeyboard version 1.11.7137, installed from F-Droid. Phone: Xiaomi POCO M6 PRO 4G. OS: Hyper 1.0.1.0.UNFIDXM Android version: 14.
> > > > > > The same app version (AnySoftKeyboard V.1.11.7137) is installed on a Xiaomi Redmi Note 8 Pro smartphone (Android version: 09; OS: MIUI Global Stable 11.0.2.0(PGGIDXM)) and there's no such issue. I'm inclined to think the issue appeared due to an android version, if the android version is above the 9th version, then the mentioned issue might appear.
> > > > > 
> > > > > 
> > > > > Hi, the issue was fixed actually and isnt there on latest beta/alpha.
> > > > 
> > > > 
> > > > I wish, but alas...Perhaps, I've missed smth., but could you clarify about which version you wrote? Because the latest AnySoftKeyboard version available ![Screenshot_2024-12-26-00-40-47-657_com opera browser-edit](https://private-user-images.githubusercontent.com/192604990/398601212-7e8b588b-972b-4c63-9c08-08cc1ab8e0f9.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUxNjM2ODgsIm5iZiI6MTczNTE2MzM4OCwicGF0aCI6Ii8xOTI2MDQ5OTAvMzk4NjAxMjEyLTdlOGI1ODhiLTk3MmItNGM2My05YzA4LTA4Y2MxYWI4ZTBmOS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyNVQyMTQ5NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yN2ZkMmQ0NjZjMDJlZTFkZmVjNWZjZjhhMDczYzBkYWMzOTc1MDZlZDQyOTIwZGQxZjU2MGIxNDVmM2ExMTg1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.lEKTe8MjLAKnoI7oJdT0JlMsLT9L6bFRn8UhpalUKMs) on F-droid is the Version 1.11.7137 (7137) (https://f-droid.org/packages/com.menny.android.anysoftkeyboard/), and that is the one I wrote about.
> > > 
> > > 
> > > The fdroid version is quite old actually. I always recommend people to use the latest beta/alpha from play store or github actions respectively. Current beta that i use is version 1.12.762
> > 
> > 
> > Thank you for the info. After reading your reply, I tried to find the beta version and I couldn't. There is no beta/alpha version on GitHub, in Google Play Store or on any third party website (according to Google search engine results). Could you enlighten me from where I can download AnySoftKeyboard version 1.12.762? I found v. 1.12.138 on apkmirror. com. Anyway, you helped me to solve the issue. The version 1.12.138 works fine, there's no more "double entries in clipboard" issue. THANK YOU!
> > ![Screenshot_2024-12-26-01-14-29-415_com opera browser-edit](https://private-user-images.githubusercontent.com/192604990/398603915-62821f1c-ec02-4dae-a574-f5c6dcb1681a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUxODI1MTgsIm5iZiI6MTczNTE4MjIxOCwicGF0aCI6Ii8xOTI2MDQ5OTAvMzk4NjAzOTE1LTYyODIxZjFjLWVjMDItNGRhZS1hNTc0LWY1YzZkY2IxNjgxYS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyNlQwMzAzMzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZjg1NzNmNWQ5NmU3YWNkZGRmOWQ4NzkyOWQ0NTJlMTZhNTViZTg3ZDlkOWNkOTBiZTY0NmM1Njk2ZDk0OTEzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.EIzZlBtOCkJpN24N7lDXTkHmajWLd6mvCq7IHerJnG4) ![Screenshot_2024-12-26-02-04-08-519_com opera browser-edit](https://private-user-images.githubusercontent.com/192604990/398603929-bf97f6d3-f0e1-496f-a572-fc1efb5e36ec.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUxODI1MTgsIm5iZiI6MTczNTE4MjIxOCwicGF0aCI6Ii8xOTI2MDQ5OTAvMzk4NjAzOTI5LWJmOTdmNmQzLWYwZTEtNDk2Zi1hNTcyLWZjMWVmYjVlMzZlYy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyNlQwMzAzMzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02Y2IyYzAyODIxYTczYjNlOTM5YTQ3NzJlYTZiMTI3MzEzZjRkMzc3OWUxOGZmMmJmYWQyODIxNmFhZDQ4ZTY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.U9MC0p_rI-1J_Lb2rKsWkqpvPD2DYmTCxIVgeGjF-5g)
> 
> you need to join beta program on play store in the app page, it is usually at the bottom of the page. Once you have joined it you will get beta updates.
> 
> for alpha you need to go to github actions menu and there find the title ime main alpha, and after clicking on it you scroll down to the bottom and download the apks file. for example https://github.com/AnySoftKeyboard/AnySoftKeyboard/actions/runs/12484579720
> 
> do note that both cant be upgraded over due to signature mismatch so you need to clean install the app if switching between beta/alpha.
> 
> if you are comfortable i post the beta builds in this telegram channel here as well for my own purpose. https://t.me/fossbeta

I'm truly grateful for your instructions! They helped me a lot, as it turned out I am not a bright github newbie (though before asking any question I searched for the info in the Internet, cause, you know, it's just lazy & stupid, when one keeps on being needy, asking simple questions instead of looking up/for their answers exploiting some search engine, not wasting someone's time to type answers).
I joined your telegram group, it's very convenient to download from there, as I had turned off Google Play Store (I had my reasons 😄).
BIG THANKS, wonderful man!
