### ISSUE TITLE
keyboard problem

### ISSUE THREAD

**Issue by krizisi** [AnySoftKeyboard/AnySoftKeyboard#4513]
The keyboard and bottom bar overlap each other.

![Image](https://github.com/user-attachments/assets/64d1323d-18d2-44ba-9acf-22d437b6dab6)

**Comment by Sayum24** [comment]
Having the same issue in Version **1.13.277**

The problem is that the keyboard is displaying below the bottom navigation bar of android.

<img width="1080" height="1104" alt="Image" src="https://github.com/user-attachments/assets/a1031be5-1f1e-4a94-af31-cf8c204be938" />

**Comment by gatefield** [comment]
Same problem (V 1.13.277). Temporary solution: changing keyboard app and change back.

**Comment by newash** [comment]
Same for the last couple of updates (even the latest 1.13.293).

**Comment by krizisi** [comment]
> Same problem (V 1.13.277). Temporary solution: changing keyboard app and change back.

That's even more annoying. There was an update on November 14, but the problem remains unresolved.

**Comment by krizisi** [comment]
@menny   Please solve this problem. I installed the old version V 1.12.891 and this version works fine. It doesn't have these problems, but I can't update it

**Comment by menny** [comment]
Thanks for reporting.
Can you provide:
- os version
- device model
- reproduction scenario
- any workaround you have found

**Comment by CarManBelarus** [comment]
I can confirm I'm experiencing very similar issue but i believe it has the same source.

For me it is not the Android system navigation bar, but **the keyboard's own utility bar** (the one with the 'hide keyboard' and 'switch input method' buttons) that is overlapping the bottom row of keys (like the spacebar).

Here are my device details:
*   **Device:** Nothing Phone (2a)
*   **OS:** Nothing OS 3.2 (Build: Pacman-V3.2-250904-1648)
*   **Android Version:** 15
*   **AnySoftKeyboard Version:** v1.13.293

The temporary solution of switching to another keyboard app and then back to AnySoftKeyboard seem to work, but the issue eventually returns.

<img width="1084" height="881" alt="Image" src="https://github.com/user-attachments/assets/3ad4055a-c265-4a58-9e83-7b9c84e7508c" />
<img width="1084" height="822" alt="Image" src="https://github.com/user-attachments/assets/85cf7ca1-8b4a-41b3-a6c3-71832f95510f" />

**Comment by krizisi** [comment]
android version: android 15.
device: oneplus 12
*AnySoftKeyboard Version:* v1.13.293 and V1.13.277.
Clearing the cache and changing the keyboard to another one and back helped
temporarily. But ultimately it didn't fix it.

**Comment by krizisi** [comment]
I installed an older version (v1.12.891) where this setting is present and
it works fine.

**Comment by krizisi** [comment]
I installed an older version (v1.12.891) where this setting is present and it works fine.

![Image](https://github.com/user-attachments/assets/10a00343-6956-4867-a29e-f068e485c99a)

**Comment by gatefield** [comment]
Android 16, Pixel 9a
happens randomly
Workaround: fast change keyboard (to gboard and back to ASK)  via globe
button in bottom bar lifts the keyboard up


Menny Even Danan ***@***.***> schrieb am Mo., 17. Nov. 2025,
00:59:

**Comment by menny** [comment]
I've merged a fix (I think I did, repro is not easy on my device).
You should have the release in Google Play Alpha channel

**Comment by krizisi** [comment]
@menny  The same problem remains in version 1.13.305.

![Image](https://github.com/user-attachments/assets/7b19e6c1-4383-4186-8876-2ce2c6202450)

**Comment by newash** [comment]
yeah, still in 1.13.305 🙁 

but I figured another workaround (not sure if existed before): if I change the orientation of the screen and change it back, the overlapping is gone again ...for a while.

And I'm sure you checked the recent changes already, but this thing was really just introduced a week or two ago. Definitely not before the 29. October commit.

**Comment by menny** [comment]
A new (possible) fix was release with version 1.13.315
Please, let me know.

**Comment by krizisi** [comment]
> A new (possible) fix was release with version 1.13.315 Please, let me know.

It's working fine at the moment. I'll let you know if anything changes.
