### ISSUE TITLE
every other swipe up from space produce key input rather than extension keyboard

### ISSUE THREAD

**Issue by digi-owl** [AnySoftKeyboard/AnySoftKeyboard#767]
### Steps to reproduce
1. swipe up from space bar

### Expected behaviour
extension keyboard (housing arrow keys etc) shows. 

### Actual behaviour
If you have had the extension keyboard out once, and wants to bring it out again, the swipe instead gets interpreted as a key press for whatever key you stop on.

**Android OS version:**
4,2

**Device manufacturer and model:**
Huawei ascend P6

**List of installed add-ons (like languages, or themes):**
Norwegian keyboard, but this happens even on the built in english one.

**Comment by digi-owl** [comment]
Err, i just noticed that i got the extension and utility keyboard confused. Sorry about that.

**Comment by menny** [comment]
This was fixed with the latest beta build. Can you verify that it works for you?

**Comment by digi-owl** [comment]
Sorry to say, but i am still seeing the problem on the beta build.
