### ISSUE TITLE
Suggestion of greek accented characters not working properly

### ISSUE THREAD

**Issue by dim-geo** [AnySoftKeyboard/AnySoftKeyboard#921]
### Steps to reproduce
1.Start typing a greek word and use the non accented character instead of the accented (correct) one
Example: Typing: ανεμος Intention to write: άνεμος

### Expected behaviour
Suggestion bar should propose the correct one (άνεμος)

In fact when I start to type something suggestion bar should take into account that I may not have accented properly a character before

### Actual behaviour
 Suggestion bar does not propose at all the correct one (άνεμος)

**Android OS version:**
6

**Device manufacturer and model:**
LG G3

**List of installed add-ons (like languages, or themes):**
greek language, ssh keyboard

**Comment by Zykino** [comment]
I have the same in french (was about to report it)
Simple words like "même" or "été" are not proposed (even in last position) when I write the same word without accent.

*Android* 7 on OnePlus 3 (OxygenOS 4.0.3)

*adds-on*
French language, azerty/bépo

**Comment by menny** [comment]
Fixed now. Will be available in the beta release (probably later today).

Is anyone here on the beta channel and can verify?

**Comment by dim-geo** [comment]
Just joined beta, will test when ready.
Thanks for fixing this!

Please take a look [https://github.com/AnySoftKeyboard/AnySoftKeyboardTools/issues/7](url) I have created a very good Greek dictionary (800000 words) and I cannot use it.

**Comment by dim-geo** [comment]
I have version 1.8.679 and it's not fixed yet. Is this the beta version where it's fixed?

**Comment by menny** [comment]
It is fixed with version 1.8.689, which is rolling out at the moment

**Comment by dim-geo** [comment]
It's working!
Please work on lifting the dictionary size.
It's common problem for many languages.
Thank you!

**Comment by menny** [comment]
👍
